---
title: KIA YÊN NGHĨA | LIÊN HỆ 0346 084 666
timezone: UTC
collections:
  cerato:
    title: Cerato
    output: true
  morning:
    title: Morning
    output: true
  optima:
    title: Optima
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  rondo:
    title: Rondo
    output: true
  sedona:
    title: Sedona
    output: true
  seltos:
    title: Seltos
    output: true
  soluto:
    title: Soluto
    output: true
  sorento:
    title: Sorento
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: cars/*
  values:
    layout: detail
name: KIA YÊN NGHĨA
email: duongvu8520@gmail.com
phone: 0346 084 666
description: Kia Yên Nghĩa - Phân phối xe KIA chính hãng giá tốt. Nhiều quà tặng giá
  trị. Liên hệ ngay! HT Vay tối đa các Ngân Hàng, LS tốt nhất. HS nợ xấu. Thủ tục
  nhanh gọn. Sẵn Xe + Đủ Màu Giao Ngay. Bảo Hành Dài Hạn. Hỗ Trợ ĐKĐK. Lái Thử Xe
  Miễn Phí. Phụ Kiện Chính Hãng.
baseurl: ''
url: dailykia5s.com
permalink: "/:title/"
author: Duong Vu
img: "/assets/images"
fb: https://facebook.com/Kiayennghia
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-figure
collections_dir: cars
paginate: 6
paginate_path: page:num/
markdown: kramdown
