---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: cars
  label: Content
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _sorento
  label: Sorento
  create: all
  match: "**/*"
- type: directory
  path: _soluto
  label: Soluto
  create: all
  match: "**/*"
- type: directory
  path: _seltos
  label: Seltos
  create: all
  match: "**/*"
- type: directory
  path: _sedona
  label: Sedona
  create: all
  match: "**/*"
- type: directory
  path: _rondo
  label: Rondo
  create: all
  match: "**/*"
- type: directory
  path: _optima
  label: Optima
  create: all
  match: "**/*"
- type: directory
  path: _morning
  label: Morning
  create: all
  match: "**/*"
- type: directory
  path: _cerato
  label: Cerato
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
